version: '3.8'

services:
  frontend:
    build:
      context: ./demo
    image: sumithaapvr/book-app:${VERSION:-latest}
    ports:
      - "4812:80"
    restart: unless-stopped
    container_name: my-book-app
